### ISSUE TITLE
GOOD LUCK!

### ISSUE THREAD

**Issue by gt732** [johndpope/MIMO-hack#6]
This is a crazy task but good luck to you! Looking forward to seeing if you can pull this off!

**Comment by johndpope** [comment]
thanks for the encourgement  - i've been distracted on a tensorflow port of IMF neural video codecs - https://github.com/johndpope/IMF/tree/feat/tensorflow-js  which i did manage to get the pytorch version working. with the future code release supposedly coming of MIMO - i put this on hold... lets wait and see.
