### ISSUE TITLE
How to get the identity image?

### ISSUE THREAD

**Issue by 1zeryu** [johndpope/MIMO-hack#8]
Great open source work! But how can I get the identify image in training code?
In original paper, it said that "Considering the efficiency, we employ a simplified method that directly transforms the posed human image to the canonical result in standard A-pose using a pretrained human repose model."
Thx.

**Comment by johndpope** [comment]
thx for encouragement - when i picked apart this paper - i have to backtrack to cover the en3d stuff (which is missing code) i started to flesh this out - but author said code is coming so kinda abandoned this effort. 
https://github.com/johndpope/en3d

**Comment by 1zeryu** [comment]
This helped me a lot, thx again!
